name: Build Android APK
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        # تم التحديث إلى v4 (وهي تدعم الإصدارات الأحدث)
        uses: actions/checkout@v4

      - name: Setup Java JDK
        # تم التحديث إلى v4 بدلاً من v3
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Node.js
        # تم التحديث إلى v4 بدلاً من v3
        uses: actions/setup-node@v4
        with:
          node-version: '20' # يمكنك استخدام 20 أو 22 هنا

      - name: Install Cordova
        run: npm install -g cordova

      - name: Build Android
        run: |
          cordova platform add android
          cordova build android --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Pulse-Yemen-Release
          path: platforms/android/app/build/outputs/apk/release/*.apk
