name: Build Android APK
on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Prepare Project and Plugins
        run: |
          # إضافة المنصة
          cordova platform add android@12.0.0
          
          # تحميل الإضافة مباشرة من GitHub لتجنب خطأ الإصدارات في npm
          cordova plugin add https://github.com/nexage/cordova-plugin-unityads.git --save
          
          # قبول رخص أندرويد
          echo y | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Build Android APK
        run: |
          # البناء بصيغة APK جاهزة للتثبيت
          cordova build android --release --device -- --packageType=apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Pulse-Yemen-Final
          path: platforms/android/app/build/outputs/apk/release/*.apk
