name: Build Android APK
on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.7'

      - name: Install Cordova
        run: npm install -g cordova

      # خطوة مهمة جداً لقبول الرخص وتثبيت المكونات الناقصة
      - name: Install Android SDK Components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-33" "build-tools;33.0.2"

      - name: Build Android
        run: |
          cordova platform add android@12.0.0 --non-interactive
          cordova build android --release --device -- --packageType=apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Pulse-Yemen-Release
          path: platforms/android/app/build/outputs/apk/release/*.apk
